_BASE_: config.yaml
MODEL:
  META_ARCHITECTURE: "RSDA_Seg"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "RSDA_Seg_Head"
    IN_FEATURES: ["res2", "res3", "res4"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 17
    TRAIN_CLASS_JSON: "datasets/DLRSD.json"
    TEST_CLASS_JSON: "datasets/DLRSD.json"
    CLIP_PRETRAINED: "ViT-B/16"
    PROMPT_DEPTH: 0
    PROMPT_LENGTH: 0
    TEXT_GUIDANCE_DIM: 512
    TEXT_GUIDANCE_PROJ_DIM: 128
    APPEARANCE_GUIDANCE_DIM: 512
    APPEARANCE_GUIDANCE_PROJ_DIM: 128
    DECODER_DIMS: [64, 32]
    DECODER_GUIDANCE_DIMS: [256, 128]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16]
    # DINO
    USE_CLIP_CORR: True 
    USE_DINO_CORR: True 
    FUSION_TYPE: "simple_separate"  # simple_separate simple_mean simple_concatenation
    DECODER_CLIP_GUIDANCE_DIMS: [256,128] 
    DECODER_CLIP_GUIDANCE_PROJ_DIMS: [32,16] 
    DECODER_DINO_GUIDANCE_DIMS: [256,128] 
    DECODER_DINO_GUIDANCE_PROJ_DIMS: [32,16] 
    NUM_LAYERS: 2
    NUM_HEADS: 4
    USE_EFFICIENT: False
    HIDDEN_DIMS: 128
    POOLING_SIZES: [2, 2]
    FEATURE_RESOLUTION: [24, 24]
    WINDOW_SIZES: 12
    ATTENTION_TYPE: "linear"
    CLIP_FINETUNE: "attention"
    # rotate
    USE_ROTATE: True
    # clip_remote
    USE_REMOTE_CLIP: True
    CLIP_REMOTE_FINETUNE: "frozen"
    CLIP_PRETRAINED_REMOTE: "ViT-B/32"       
    CLIP_PRETRAINED_WEIGHTS_REMOTE: "./pretrained/RemoteCLIP-ViT-B-32.pt"
    # dino
    USE_REMOTE_DINO: True 
    DINO_FINETUNE: "frozen"
    DINO_WEIGHTS: "./pretrained/DINO_WEIGHTS.pth"
  PROMPT_ENSEMBLE_TYPE: "single"
INPUT:
  MIN_SIZE_TRAIN: (384, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (384, 384)
  SIZE_DIVISIBILITY: 384 
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
DATASETS:
  TRAIN: ("DLRSD_train_sem_seg",)
  TEST: ("DLRSD_val_sem_seg",)
SOLVER:
  IMS_PER_BATCH: 4 
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.0002
  MAX_ITER: 60000
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 0.01
TEST:
  EVAL_PERIOD: 5000
  